# Generated by Django 5.1.3 on 2024-11-29 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_basket"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты"},
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={
                "verbose_name": "Категория продуктов",
                "verbose_name_plural": "Категории продуктов",
            },
        ),
    ]
